{"timestamp": "2025-08-15T18:50:01.429266", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140381450651328, "thread_name": "Thread-6 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.431180", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140380871849664, "thread_name": "Thread-10 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.431757", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140380855064256, "thread_name": "Thread-12 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.432082", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140381433865920, "thread_name": "Thread-8 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.433736", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140380821493440, "thread_name": "Thread-16 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.434371", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140380309800640, "thread_name": "Thread-20 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.435071", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140380838278848, "thread_name": "Thread-14 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.436377", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140380293015232, "thread_name": "Thread-22 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.437510", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379798107840, "thread_name": "Thread-24 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.437922", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140380326586048, "thread_name": "Thread-18 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.438330", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379781322432, "thread_name": "Thread-26 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.439951", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379764537024, "thread_name": "Thread-28 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.441217", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379747751616, "thread_name": "Thread-30 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.441953", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379252844224, "thread_name": "Thread-32 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.442343", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379236058816, "thread_name": "Thread-34 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.443007", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379219273408, "thread_name": "Thread-36 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.443851", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379127019200, "thread_name": "Thread-38 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.444601", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379110233792, "thread_name": "Thread-40 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:01.446032", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3686, "thread_id": 140379093448384, "thread_name": "Thread-42 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:01"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.660192", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140577635038912, "thread_name": "Thread-6 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.661846", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140577618253504, "thread_name": "Thread-8 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.663378", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140577601468096, "thread_name": "Thread-10 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.664043", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140577584682688, "thread_name": "Thread-12 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.664157", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140577089775296, "thread_name": "Thread-14 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.665874", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140577072989888, "thread_name": "Thread-16 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.666454", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140577056204480, "thread_name": "Thread-18 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.667581", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140576561297088, "thread_name": "Thread-20 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.668444", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140576544511680, "thread_name": "Thread-22 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.669163", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140576527726272, "thread_name": "Thread-24 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.669334", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140576510940864, "thread_name": "Thread-26 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.670197", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140576016033472, "thread_name": "Thread-28 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.670739", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140575999248064, "thread_name": "Thread-30 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.671839", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140575982462656, "thread_name": "Thread-32 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.672702", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140575621772992, "thread_name": "Thread-34 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.673228", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140575604987584, "thread_name": "Thread-36 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.674502", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140575588202176, "thread_name": "Thread-38 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.674867", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140575571416768, "thread_name": "Thread-40 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
{"timestamp": "2025-08-15T18:50:17.675207", "level": "ERROR", "logger": "app.utils.cache", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "module": "cache", "function": "_collect_metrics", "line_number": 678, "process_id": 3784, "thread_id": 140575554631360, "thread_name": "Thread-42 (monitoring_loop)", "extra": {"taskName": null, "color": "\u001b[31m", "reset": "\u001b[0m", "message": "Metrics collection error: Error 111 connecting to localhost:6379. Connection refused.", "asctime": "2025-08-15 18:50:17"}, "application": {"name": "PurSight Enterprise Data Governance", "version": "2.0.0", "environment": "development"}}
